# Generated by Django 5.1.4 on 2025-01-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramos'), ('LT', 'Litros'), ('GR', 'Gramos')], max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='MiApp.contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='MiApp.articulo')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='MiApp.contenedor')),
            ],
        ),
    ]
