# Generated by Django 5.1.4 on 2025-01-25 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_contenedor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contenedor',
            constraint=models.UniqueConstraint(fields=('nombre', 'usuario'), name='unique_contenedor_per_user'),
        ),
    ]
